//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoNotes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoNotes.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the App Seed..
        /// </summary>
        internal static string AppSeedGetFailed {
            get {
                return ResourceManager.GetString("AppSeedGetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create and save the App Seed.
        /// </summary>
        internal static string AppSeedSetFailed {
            get {
                return ResourceManager.GetString("AppSeedSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Signature was bad. Rejecting..
        /// </summary>
        internal static string BadSignature {
            get {
                return ResourceManager.GetString("BadSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to decompress text.
        /// </summary>
        internal static string DecompressionError {
            get {
                return ResourceManager.GetString("DecompressionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption Failed.
        /// </summary>
        internal static string DecryptionFailed {
            get {
                return ResourceManager.GetString("DecryptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Failed.
        /// </summary>
        internal static string EncryptionFailed {
            get {
                return ResourceManager.GetString("EncryptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.txt.
        /// </summary>
        internal static string ErrorFileName {
            get {
                return ResourceManager.GetString("ErrorFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Keys (This could take a bit).
        /// </summary>
        internal static string GenerateKeys {
            get {
                return ResourceManager.GetString("GenerateKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still Generating Keys... .
        /// </summary>
        internal static string GenerateKeys1 {
            get {
                return ResourceManager.GetString("GenerateKeys1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A 4096bit key takes awhile... please wait.
        /// </summary>
        internal static string GenerateKeys2 {
            get {
                return ResourceManager.GetString("GenerateKeys2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Random Seed.
        /// </summary>
        internal static string GeneratingRandomSeed {
            get {
                return ResourceManager.GetString("GeneratingRandomSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating salt.
        /// </summary>
        internal static string GeneratingSalt {
            get {
                return ResourceManager.GetString("GeneratingSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN must be a number 1,000 - 9,999.
        /// </summary>
        internal static string InvaildPIN {
            get {
                return ResourceManager.GetString("InvaildPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password and/or PIN could not be validated. Login denied. .
        /// </summary>
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppRSAKeyStore.
        /// </summary>
        internal static string KeyStoreName {
            get {
                return ResourceManager.GetString("KeyStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading RSA Key.
        /// </summary>
        internal static string LoadRSAKey {
            get {
                return ResourceManager.GetString("LoadRSAKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message / Text Box Cannot Be Blank.
        /// </summary>
        internal static string NullMessage {
            get {
                return ResourceManager.GetString("NullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Cannot Be Blank.
        /// </summary>
        internal static string NullPassword {
            get {
                return ResourceManager.GetString("NullPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Cannot Be Blank.
        /// </summary>
        internal static string NullPIN {
            get {
                return ResourceManager.GetString("NullPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivateKey.asc.
        /// </summary>
        internal static string PrivateKeyFileName {
            get {
                return ResourceManager.GetString("PrivateKeyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicKey.asc.
        /// </summary>
        internal static string PublicKeyFileName {
            get {
                return ResourceManager.GetString("PublicKeyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RandomSeed.txt.
        /// </summary>
        internal static string RandomSeedFileName {
            get {
                return ResourceManager.GetString("RandomSeedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.enc.
        /// </summary>
        internal static string RSAKeyFileName {
            get {
                return ResourceManager.GetString("RSAKeyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not decrypt the salt!.
        /// </summary>
        internal static string SaltDecryptionFailed {
            get {
                return ResourceManager.GetString("SaltDecryptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt.txt.
        /// </summary>
        internal static string SaltFileName {
            get {
                return ResourceManager.GetString("SaltFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filed to generate the salt.
        /// </summary>
        internal static string SaltGenerateFailure {
            get {
                return ResourceManager.GetString("SaltGenerateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save key.
        /// </summary>
        internal static string SaveKeyFailure {
            get {
                return ResourceManager.GetString("SaveKeyFailure", resourceCulture);
            }
        }
    }
}
